services:
  postgres:
    image: postgres:17
    container_name: social_postgres
    restart: always
    environment:
      POSTGRES_DB: social_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: social_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

#  app:
#    build: .
#    container_name: social_app
#    depends_on:
#      - postgres
#      - redis
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/social_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#      SPRING_MAIL_HOST: smtp.gmail.com
#      SPRING_MAIL_PORT: 587
#      SPRING_MAIL_USERNAME: huydcvt236ptit@gmail.com
#      SPRING_MAIL_PASSWORD: urtgxgkvhggktfzx
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "true"
#    ports:
#      - "8080:8080"

volumes:
  postgres_data:
  redis_data:
