server:
  port: 8080

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      static-locations: file:uploads/
      add-mappings: true

jwt:
  key:
    private-key: classpath:keys/private.pem
    public-key: classpath:keys/public.pem
  expiration: 86400000

springdoc:
  default-produces-media-type: application/json

application:
  file:
    uploads:
      media-output-path: uploads/

logging:
  level:
    root: info
    sql: info
    web: trace