spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_db
    username:
    password:
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port:
    username: #your_email
    password: #app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true