spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_db?timeZone=Asia/Ho_Chi_Minh
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: huydcvt236ptit@gmail.com
    password: "urtgxgkvhggktfzx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: localhost
      port: 6379

  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, file:./uploads/
      cache:
        cachecontrol:
          max-age: 86400
          cache-public: true

file:
  image-upload: uploads/images/
  video-upload: uploads/videos/

application:
  file:
    uploads:
      media-output-path: uploads/
