spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/social_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:huydcvt236ptit@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:urtgxgkvhggktfzx}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: redis
      port: 6379

  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, file:app/uploads/

file:
  image-upload: app/uploads/images/
  video-upload: app/uploads/videos/

application:
  file:
    uploads:
      media-output-path: app/uploads/
