spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


  mail:
    host: smtp.gmail.com
    port: 587
    username: huydcvt236ptit@gmail.com
    password: "urtgxgkvhggktfzx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: localhost
      port: 6379