server:
  port: 8080

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, file:./uploads/
      cache:
        cachecontrol:
          max-age: 86400
          cache-public: true
  output:
    ansi:
      enabled: ALWAYS

jwt:
  key:
    private-key: classpath:keys/private.pem
    public-key: classpath:keys/public.pem
  expiration: 86400000

springdoc:
  default-produces-media-type: application/json

application:
  file:
    uploads:
      media-output-path: backend/uploads

logging:
  level:
    root: INFO
    web: TRACE
  #    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  #    org.apache.coyote.http11: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) %green(%M) %yellow(%L) - %msg%n"