server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  key:
    private-key: classpath:keys/private.pem
    public-key: classpath:keys/public.pem
  expiration: 86400000

logging:
  level:
    root: INFO
    web: TRACE
    org.springframework.data.neo4j: DEBUG
